name: test

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  run:
    continue-on-error: True
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] # TODO: add macos-latest, windows-latest ?
        python-version: [3.7, 3.8, 3.9]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install -e ."[dev]"

    - name: Unit tests and coverage
      run: |
        tox -e py${{ matrix.python-version }}
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: false
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v1
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
#        file: ./coverage.xml
#        flags: unittests
#        name: codecov-umbrella
#        fail_ci_if_error: true
